# Generated by Django 3.0.3 on 2021-06-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0002_auto_20210614_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(related_name='photos', to='formulas.Tag'),
        ),
    ]
