# Generated by Django 3.0.3 on 2021-06-20 22:35

from django.db import migrations, models
import formulas.models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0003_auto_20210616_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='content',
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.ImageField(null=True, upload_to=formulas.models.user_photos_directory_path),
        ),
    ]
