# Generated by Django 3.0.3 on 2021-06-21 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0004_auto_20210620_1735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_contex',
            new_name='photo_context',
        ),
    ]
