# Generated by Django 3.0.3 on 2021-06-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0005_auto_20210621_1012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('photo', 'profile')},
        ),
    ]
