# Generated by Django 3.0.3 on 2021-06-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0009_auto_20210623_1451'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='photoclassification',
            constraint=models.UniqueConstraint(fields=('subject', 'exam_number'), name='subject and exam number must be unique'),
        ),
    ]
