# Generated by Django 3.0.3 on 2021-08-14 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulas', '0011_auto_20210628_1438'),
    ]

    operations = [
        migrations.RunSQL(sql="""
            ALTER TABLE "formulas_photo" ADD COLUMN "search_vector" tsvector
            GENERATED ALWAYS AS (
            setweight(to_tsvector('english', coalesce(name, '')), 'A') ||
            setweight(to_tsvector('english', coalesce(description, '')), 'B') ||
            ' '
            ) STORED NULL; CREATE INDEX search_vector ON formulas_photo
            USING GIN(search_vector);
        """, reverse_sql="""
            ALTER TABLE "formulas_photo" DROP COLUMN "search_vector";
        """)
    ]
